### ISSUE TITLE
'dtIoUs' key error

### ISSUE THREAD

**Issue by saranadeem01** [fiveai/saod#1]
Hi, Thank you for sharing the code. 
During evaluation, in saod_evaluation.py>Calibration>prepare_input, I got error at a line 101;

dtIoU = np.concatenate(
                        [e['dtIoUs'][:, 0:maxDet] for e in E], axis=1)[:, inds]

Can you please help me with this, what I am missing?

**Comment by kemaloksuz** [comment]
Hi, you should be using pycocotools with LRP modification here: https://github.com/kemaloksuz/LRP-Error

Then, you will be getting DtIoU after evaluateImg function: https://github.com/kemaloksuz/LRP-Error/blob/ec408f3c8a3bc3408e0fdc84469e0101245f3bfb/pycocotools/pycocotools/cocoeval.py#L322

To do so, simply uninstall your pycocotools and install the one I shared please.

**Comment by saranadeem01** [comment]
Resolved by re-installing. Thanks for the reply.
