### ISSUE TITLE
How to do LA-ECE computation for already calibrated model?

### ISSUE THREAD

**Issue by saranadeem01** [fiveai/saod#2]
Hi,
I have two concerns regarding reporting the LAECE measure value for an already calibrated model. As I am new to this domain, your guidance would be greatly appreciated.

1) I aim to compute only the LA-ECE measure of an object detector that has already been calibrated using another method. What values should be set for the TP validation threshold and detection level threshold in general?

2) The LRP value computed by the 'COCO_evaluation' option differs from the 'Evaluate the Calibration Performance and Accuracy' option. Currently, I am using '--detection_level_threshold' = -1 and '--tau' = 0.50 and comparing the results with the Coco optimal LRP@IOU=0.5.

Many thanks.

**Comment by selimkuzucu** [comment]
Hiya sara4585,

We have just released our new pre-print on arXiv, [On Calibration of Object Detectors: Pitfalls, Evaluation and Baselines](https://arxiv.org/abs/2405.20459) with an accompanying library, [detection_calibration](https://github.com/fiveai/detection_calibration). I think you can easily obtain the results you are seeking easily through that library.

Please let me know if you need any further assistance on this, I'd be more than happy to help.
